# Generated by Django 5.0 on 2023-12-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n        این نام صرفا جنبه نمایشی دارد و کاربردی در سیستم\n        نخواهد داشت', max_length=50, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name_plural': 'گروه بندی',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n        این نام ربات در نام اکانت قرار خواهد گرفت', max_length=50, verbose_name='نام ربات')),
                ('username', models.CharField(help_text='\n        نام کاربری ربات در اینیستا گرام', max_length=100, verbose_name='نام کاربری ربات')),
                ('password', models.CharField(help_text='\n        رمزعبور اکانت ربات در اینیستاگرام', max_length=100, verbose_name='رمزعبور ربات')),
                ('active', models.BooleanField(default=True, help_text='\n        در صورت غیر فعال بودن این گزینه ربات کار نخواهد کرد', verbose_name='فعال')),
                ('watchMin', models.IntegerField(default=20, help_text='\n        عدد رندوم مشاهده پست ربات از این مقدار بیشتر خواهد بود', verbose_name='حداقل مشاهده پست (ثانیه)')),
                ('watchMax', models.IntegerField(default=50, help_text='\n        عدد رندوم مشاهده پست ربات از این مقدار کمتر خواهد بود', verbose_name='حداکثر مشاهده پست (ثانیه)')),
                ('delayMin', models.IntegerField(default=10, help_text='\n        عدد رندوم استراحت ربات از این مقدار بیشتر خواهد بود', verbose_name='حداقل استراحت (دقیقه)')),
                ('delayMax', models.IntegerField(default=40, help_text='\n        عدد رندوم استراحت ربات از این مقدار کمتر خواهد بود', verbose_name='حداکثر استراحت (دقیقه)')),
                ('actionMin', models.IntegerField(default=10, help_text='\n        عدد رندوم اکشن ربات از این مقدار بیشتر خواهد بود', verbose_name='حداقل اکشن')),
                ('actionMax', models.IntegerField(default=40, help_text='\n        عدد رندوم اکشن ربات از این مقدار کمتر خواهد بود', verbose_name='حداکثر اکشن')),
                ('actionCount', models.IntegerField(default=10, help_text='\n        تعداد عملیاتی که این ربات تا بحال انجام داده است', verbose_name='تعداد عملیات')),
                ('group', models.ManyToManyField(to='account.groups', verbose_name='گروه ها')),
            ],
            options={
                'verbose_name_plural': 'ربات ها',
            },
        ),
    ]
