# Generated by Django 5.0 on 2023-12-05 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('orders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ انجام اکشن')),
                ('bot', models.ForeignKey(editable=False, help_text='\n        انجام شده توسط', on_delete=django.db.models.deletion.CASCADE, to='account.accounts', verbose_name='ربات انجام دهنده')),
                ('group', models.ForeignKey(editable=False, help_text='\n        گروهی که ربات بر روی آن قرار دارد', on_delete=django.db.models.deletion.CASCADE, to='account.groups', verbose_name='گروه ربات')),
                ('order', models.ForeignKey(editable=False, help_text='\n        سفارشی که این ربات بر روی آن فعال شده است', on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='سفارش مبدا')),
            ],
        ),
    ]
