# Generated by Django 5.0 on 2023-12-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ انجام اکشن')),
                ('desc', models.TextField(blank=True, editable=False, max_length=2000, null=True, verbose_name='توضیحات')),
                ('bot', models.ForeignKey(editable=False, help_text='\n        انجام شده توسط', on_delete=django.db.models.deletion.CASCADE, to='account.accounts', verbose_name='ربات انجام دهنده')),
                ('group', models.ForeignKey(editable=False, help_text='\n        گروهی که ربات بر روی آن قرار دارد', on_delete=django.db.models.deletion.CASCADE, to='account.groups', verbose_name='گروه ربات')),
                ('order', models.ForeignKey(blank=True, editable=False, help_text='\n        سفارشی که این ربات بر روی آن فعال شده است', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='سفارش مبدا')),
            ],
            options={
                'verbose_name_plural': 'گزارشات',
            },
        ),
    ]
