# Generated by Django 5.0 on 2023-12-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='group',
            field=models.ForeignKey(blank=True, editable=False, help_text='\n        گروهی که ربات بر روی آن قرار دارد', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.groups', verbose_name='گروه ربات'),
        ),
    ]
