# Generated by Django 5.0 on 2023-12-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'گزارشات'},
        ),
    ]
