# Generated by Django 5.0 on 2023-12-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n        این گزینه صرفا جنبه نمایشی دارد', max_length=100, verbose_name='نام سفارش')),
                ('campaignID', models.CharField(help_text='\n        آیدی کمپین برای انجام عملیات\n        ربات بر روی گزینه تگ های این کمپین\n        اکشن انجام خواهد داد', max_length=100, verbose_name='آیدی کمپین')),
                ('status', models.IntegerField(choices=[(0, 'فعال'), (1, 'غیر فعال')], default=0, help_text='\n        وضعیت انجام سفارش تعیین کننده فعالیت گروه است\n        در صورت انتظار بودن این گزینه ربات های گروه این مورد را\n        انجام خواهند داد. در غیر اینصورت انجام نخواهد شد', verbose_name='وضعیت انجام')),
                ('start', models.TimeField(help_text='\n        در این زمان گروه ربات ها شروع به فعالیت خواهند کرد', verbose_name='ساعت شروع گروه')),
                ('end', models.TimeField(help_text='\n        در این زمان گروه ربات ها به فعالیت خود پایان خواهند داد', verbose_name='ساعت پایان گروه')),
                ('group', models.ForeignKey(help_text='\n        این سفارش توسط گروه تعیین شده انجام\n        خواهد شد', on_delete=django.db.models.deletion.CASCADE, to='account.groups', verbose_name='گروه عامل')),
            ],
            options={
                'verbose_name_plural': 'کمپین ها',
            },
        ),
    ]
